<?php
//styles generated by customizer
function directory_theme_customize_css()
{
	/**
	 * Table of Contents
	 *
	 * 1.0 - General
	 *   1.1 - Site Identity
	 *   	1.1.1 - Blog Name
	 *      1.1.2 - Tagline
	 *      1.1.3 - Colors
	 *   1.2 - Spacing
	 *      1.2.1 - Desktop Container Width
	 *      1.2.2 - Container Padding Right
	 *      1.2.3 - Container Padding Left
	 *      1.2.4 - Container Margin Right
	 *      1.2.5 - Container Margin Left
	 *   1.3 - Static Front Page
	 *      1.3.1 - Front Page
	 *   1.4 - Alert Colors
	 *      1.4.1 - Alert Warning Background Color
	 *      1.4.2 - Alert Error Background Color
	 *      1.4.3 - Alert Success Background Color
	 *      1.4.4 - Alert Info Background Color
	 *      1.4.5 - Alert Warning Text Color
	 *      1.4.6 - Alert Error Text Color
	 *      1.4.7 - Alert Success Text Color
	 *      1.4.8 - Alert Info Text Color
	 *      1.4.9 - Alert Warning Border Color
	 *      1.4.10 - Alert Error Border Color
	 *      1.4.11 - Alert Success Border Color
	 *      1.4.12 - Alert Info Border Color
	 * 	 1.5 - Button Colors
	 *      1.5.1 - Button Text Color
	 *      1.5.2 - Button Background Color
	 *      1.5.3 - Button Hover Background Color
	 *      1.5.4 - Button Border Color
	 * 2.0 - Header
	 *   2.1 - Header Top
	 *      2.1.1 - Enable Header Top Section
	 *      2.1.2 - Header Top Text Color
	 *      2.1.3 - Header Top Link Color
	 *      2.1.4 - Header Top Link Hover Color
	 * 		2.1.5 - Header Top Background Color
	 *   2.2 - Logo
	 * 		2.2.1 - Logo
	 *   2.3 - Header Image
	 * 		2.3.1 - Header Image
	 *   2.4 - Text Colors
	 * 		2.4.1 - Header Text color
	 * 		2.4.2 - Header Link color
	 *      2.4.3 - Header Link Hover Color
	 *   2.5 - Background Colors
	 * 		2.5.1 - Header Background Color
	 * 		2.5.2 - Header Border Color
	 * 		2.5.3 - Header Shadow Color
	 * 		2.5.4 - Primary Menu - Sub menu Background Color
	 *      2.5.5 - Primary Menu - Sub menu Background hover Color
	 *   2.6 - Typography
	 *   2.7 - Spacing
	 * 		2.7.1 - Header Height
	 * 		2.7.2 - Logo Margin Right
	 * 		2.7.3 - Logo Margin Left
	 * 		2.7.4 - Logo Margin Top
	 * 		2.7.5 - Primary Menu Height
	 * 		2.7.6 - Primary Menu Line Height
	 * 		2.7.7 - Primary Menu Padding Left Right
     *      2.7.8 - Header Logo Width
     *      2.7.9 - Header Menu Width
	 * 3.0 - Body
	 *   3.1 - Background Image
	 * 		3.1.1 - Background Image
	 *   3.2 - Text Colors
	 * 		3.2.1 - Body Color
	 * 		3.2.2 - h1 to h6 Color
	 * 		3.2.3 - Link Color
	 * 		3.2.4 - Link Hover Color
	 * 		3.2.5 - Link Visited Color
	 *   3.3 - Background Colors
	 * 		3.3.1 - Body Background Color
	 * 		3.3.2 - Content Box Background Color
	 * 		3.3.3 - Content Box Border Color
	 * 		3.3.4 - Content Box Shadow Color
	 *   3.4 - Typography
	 * 		3.4.1 - Font Family
	 * 		3.4.2 - Font Size
	 * 		3.4.3 - Line Height
	 *   3.5 - Spacing
	 * 4.0 - Footer
	 *   4.1 - Text Colors
	 * 		4.1.1 - Text Color
	 * 		4.1.2 - h1 to h6 Color
	 * 		4.1.3 - Link Color
	 * 		4.1.4 - Link Hover Color
	 * 		4.1.5 - Link Visited Color
	 *   4.2 - Background Colors
	 * 		4.2.1 - Footer Section Background Color
	 * 		4.2.2 - Footer Section Border Top Color
	 * 		4.2.3 - Footer Section Border Bottom Color
	 * 		4.2.4 - Footer Section Box Shadow Color
	 *   4.3 - Typography
	 *   4.4 - Spacing
	 * 5.0 - Copyright
	 * 	5.1 - Text Colors
	 * 		5.1.1 - Text Color
	 * 		5.1.2 - Link Color
	 * 		5.1.3 - Link Hover Color
	 * 		5.1.4 - Link Visited Color
	 *	5.2 - Background Colors
	 * 		5.2.1 - Copyright Section Background Color
	 * 		5.2.2 - Copyright Section Border Color
	 * 	5.3 - Typography
	 * 	5.4 - Spacing
	 * 		5.4.1 - Copyright Padding Top
	 * 		5.4.2 - Copyright Padding Bottom
	 * 	5.5 - Copyright Text
	 * 		5.5.1 - Copyright Text
	 * 		5.5.2 - Credits
	 */


//  =============================
//  1.0 - General
//  =============================
?>
<?php
	//  =============================
	//  1.1 - Site Identity
	//  =============================
	?>
		<?php
		//  =============================
		//  1.1.1 - Blog Name
		//  =============================
		?>
		<?php
		//  =============================
		//  1.1.2 - Tagline
		//  =============================
		?>
		<?php
		//  =============================
		//  1.1.3 - Colors
		//  =============================
		?>
	<?php
	//  =============================
	//  1.2 - Spacing
	//  =============================
	?>
		<?php
		//  =============================
		//  1.2.1 - Desktop Container Width
		//  =============================
		?>
			@media (min-width: 1200px) {
				.container, .geodir-common, .geodir-breadcrumb, .geodir_full_page .widget {
					width: <?php echo esc_attr(get_theme_mod('dt_container_width', DT_CONTAINER_WIDTH)); ?>;
				}
			}
		<?php
		//  =============================
		//  1.2.2 - Container Padding Right
		//  =============================
		?>
			.container, .geodir-common, .geodir-breadcrumb, .geodir_full_page .widget {
				padding-right: <?php echo esc_attr(get_theme_mod('dt_container_padding_right', DT_CONTAINER_PADDING_RIGHT)); ?>;
				padding-left: <?php echo esc_attr(get_theme_mod('dt_container_padding_left', DT_CONTAINER_PADDING_LEFT)); ?>;
				margin-right: <?php echo esc_attr(get_theme_mod('dt_container_margin_right', DT_CONTAINER_MARGIN_RIGHT)); ?>;
				margin-left: <?php echo esc_attr(get_theme_mod('dt_container_margin_left', DT_CONTAINER_MARGIN_LEFT)); ?>;
			}
		<?php
		//  =============================
		//  1.2.3 - Container Padding Left
		//  =============================
			// @see 1.2.2
		?>
		<?php
		//  =============================
		//  1.2.4 - Container Margin Right
		//  =============================
			// @see 1.2.2
		?>
		<?php
		//  =============================
		//  1.2.5 - Container Margin Left
		//  =============================
			// @see 1.2.2
		?>
	<?php
	//  =============================
	//  1.3 - Static Front Page
	//  =============================
	?>
		<?php
		//  =============================
		//  1.3.1 - Front Page
		//  =============================
		?>
	<?php
	//  =============================
	//  1.4 - Alert Colors
	//  =============================
	?>
		<?php
		//  =============================
		//  1.4.1 - Alert Warning Background Color
		//  =============================
		?>
			.alert-warning, #buddypress #message.info p {
				color: <?php echo esc_attr(get_theme_mod('dt_alert_yellow_text', DT_ALERT_YELLOW_TEXT)); ?>;
				background-color: <?php echo esc_attr(get_theme_mod('dt_alert_yellow', DT_ALERT_YELLOW)); ?>;
				border-color: <?php echo esc_attr(get_theme_mod('dt_alert_yellow_border', DT_ALERT_YELLOW_BORDER)); ?>;
			}
		<?php
		//  =============================
		//  1.4.2 - Alert Error Background Color
		//  =============================
		?>
			.alert-error, .error_msg_fix, #buddypress div#message.error p {
				color: <?php echo esc_attr(get_theme_mod('dt_alert_red_text', DT_ALERT_RED_TEXT)); ?>;
				background-color: <?php echo esc_attr(get_theme_mod('dt_alert_red', DT_ALERT_RED)); ?>;
				border-color: <?php echo esc_attr(get_theme_mod('dt_alert_red_border', DT_ALERT_RED_BORDER)); ?>;
			}
		<?php
		//  =============================
		//  1.4.3 - Alert Success Background Color
		//  =============================
		?>
			.alert-success, .sucess_msg, #buddypress div#message.updated p {
				color: <?php echo esc_attr(get_theme_mod('dt_alert_green_text', DT_ALERT_GREEN_TEXT)); ?>;
				background-color: <?php echo esc_attr(get_theme_mod('dt_alert_green', DT_ALERT_GREEN)); ?>;
				border-color: <?php echo esc_attr(get_theme_mod('dt_alert_green_border', DT_ALERT_GREEN_BORDER)); ?>;
			}
		<?php
		//  =============================
		//  1.4.4 - Alert Info Background Color
		//  =============================
		?>
			.alert-info {
				color: <?php echo esc_attr(get_theme_mod('dt_alert_blue_text', DT_ALERT_BLUE_TEXT)); ?>;
				background-color: <?php echo esc_attr(get_theme_mod('dt_alert_blue', DT_ALERT_BLUE)); ?>;
				border-color: <?php echo esc_attr(get_theme_mod('dt_alert_blue_border', DT_ALERT_BLUE_BORDER)); ?>;
			}
		<?php
		//  =============================
		//  1.4.5 - Alert Warning Text Color
		//  =============================
			// @see 1.4.1
		?>
		<?php
		//  =============================
		//  1.4.6 - Alert Error Text Color
		//  =============================
			// @see 1.4.2
		?>
		<?php
		//  =============================
		//  1.4.7 - Alert Success Text Color
		//  =============================
			// @see 1.4.3
		?>
		<?php
		//  =============================
		//  1.4.8 - Alert Info Text Color
		//  =============================
			// @see 1.4.4
		?>
		<?php
		//  =============================
		//  1.4.9 - Alert Warning Border Color
		//  =============================
			// @see 1.4.1
		?>
		<?php
		//  =============================
		//  1.4.10 - Alert Error Border Color
		//  =============================
			// @see 1.4.2
		?>
		<?php
		//  =============================
		//  1.4.11 - Alert Success Border Color
		//  =============================
			// @see 1.4.3
		?>
		<?php
		//  =============================
		//  1.4.12 - Alert Info Border Color
		//  =============================
			// @see 1.4.4
		?>
	<?php
	//  =============================
	//  1.5 - Button Colors
	//  =============================
	?>
		<?php
		//  =============================
		//  1.5.1 - Button Text Color
		//  =============================
		?>
			.dt-btn, button, input[type=button], input[type=reset], input[type=submit], p.edit-link, #buddypress form#whats-new-form input[type=submit], #buddypress .standard-form div.submit input, #buddypress .comment-reply-link, #buddypress button, #buddypress div.generic-button a, #buddypress input[type=button], #buddypress input[type=reset], #buddypress input[type=submit], #buddypress ul.button-nav li a, #buddypress input[type=submit]#notification-bulk-manage, dl.geodir-tab-head dd.geodir-tab-active a, .reply .gd_comment_replaylink .comment-reply-link, #reviewsTab #comments .comment-reply-link, #simplemodal-container #gd-basic-modal-content4 .button,
			.dt-btn:focus, button:focus, input[type=button]:focus, input[type=reset]:focus, input[type=submit]:focus, p.edit-link:focus, .reply .gd_comment_replaylink #gd_comment_replaylink:focus, #buddypress form#whats-new-form input[type=submit]:focus, #buddypress .standard-form div.submit input:focus, #buddypress .comment-reply-link:focus, #buddypress button:focus, #buddypress div.generic-button a:focus, #buddypress input[type=button]:focus, #buddypress input[type=reset]:focus, #buddypress input[type=submit]:focus, #buddypress ul.button-nav li a:focus, #buddypress input[type=submit]#notification-bulk-manage:focus, .reply .gd_comment_replaylink .comment-reply-link:focus, #reviewsTab #comments .comment-reply-link:focus, #simplemodal-container #gd-basic-modal-content4 .button:focus {
				color: <?php echo esc_attr(get_theme_mod('dt_btn_text_color', DT_BTN_TEXT_COLOR)); ?>;
				background-color: <?php echo esc_attr(get_theme_mod('dt_btn_bg_color', DT_BTN_BG_COLOR)); ?>;
				border: 1px solid <?php echo esc_attr(get_theme_mod('dt_btn_border_color', DT_BTN_BORDER_COLOR)); ?>;
			}
		<?php
		//  =============================
		//  1.5.2 - Button Background Color
		//  =============================
			// @see 1.5.2
		?>
		<?php
		//  =============================
		//  1.5.3 - Button Hover Background Color
		//  =============================
		?>
			.dt-btn:hover, button:hover, input[type=button]:hover, input[type=reset]:hover, input[type=submit]:hover, p.edit-link:hover, .reply .gd_comment_replaylink #gd_comment_replaylink:hover, #buddypress form#whats-new-form input[type=submit]:hover, #buddypress .standard-form div.submit input:hover, #buddypress .comment-reply-link:hover, #buddypress button:hover, #buddypress div.generic-button a:hover, #buddypress input[type=button]:hover, #buddypress input[type=reset]:hover, #buddypress input[type=submit]:hover, #buddypress ul.button-nav li a:hover, #buddypress input[type=submit]#notification-bulk-manage:hover, .reply .gd_comment_replaylink .comment-reply-link:hover, #reviewsTab #comments .comment-reply-link:hover, #simplemodal-container #gd-basic-modal-content4 .button:hover {
				background-color: <?php echo esc_attr(get_theme_mod('dt_btn_hover_color', DT_BTN_HOVER_COLOR)); ?>;
			}
		<?php
		//  =============================
		//  1.5.4 - Button Border Color
		//  =============================
			// @see 1.5.4
		?>
	<?php
//  =============================
//  2.0 - Header
//  =============================
	?>
	<?php
	//  =============================
	//  2.1 - Header Top
	//  =============================
	?>
		<?php
		//  =============================
		//  2.1.1 - Enable Header Top Section
		//  =============================
		?>
		<?php
		//  =============================
		//  2.1.2 - Header Top Text Color
		//  =============================
		?>
			.ds-top-header {
				color: <?php echo esc_attr(get_theme_mod('dt_header_top_text_color', DT_HEADER_TOP_TEXT_COLOR)); ?>;
			}
		<?php
		//  =============================
		//  2.1.3 - Header Top Link Color
		//  =============================
		?>
			.ds-top-header a,
			.ds-top-header a:visited {
				color: <?php echo esc_attr(get_theme_mod('dt_header_top_link_color', DT_HEADER_TOP_LINK_COLOR)); ?>;
			}
		<?php
		//  =============================
		//  2.1.4 - Header Top Link Hover Color
		//  =============================
		?>
			.ds-top-header a:hover {
				color: <?php echo esc_attr(get_theme_mod('dt_header_top_link_hover', DT_HEADER_TOP_LINK_HOVER)); ?>;
			}
		<?php
		//  =============================
		//  2.1.5 - Header Top Background Color
		//  =============================
		?>
			.ds-top-header {
				background-color: <?php echo esc_attr(get_theme_mod('dt_header_top_bg_color', DT_HEADER_TOP_BG_COLOR)); ?>;
			}
	<?php
	//  =============================
	//  2.2 - Logo
	//  =============================
	?>
		<?php
		//  =============================
		//  2.2.1 - Logo
		//  =============================
		?>
	<?php
	//  =============================
	//  2.3 - Header Image
	//  =============================
	?>
		<?php
		//  =============================
		//  2.3.1 - Header Image
		//  =============================
		?>
	<?php
	//  =============================
	//  2.4 - Text Colors
	//  =============================
	?>
		<?php
		//  =============================
		//  2.4.1 - Header Text color
		//  =============================
		?>
			.site-header {
				color: <?php echo esc_attr(get_theme_mod('header_textcolor', DT_BODY_COLOR)); ?>;
			}
		<?php
		//  =============================
		//  2.4.2 - Header Link color
		//  =============================
		?>
			.site-header a, .site-header a:visited {
				color: <?php echo esc_attr(get_theme_mod('dt_header_link_color', DT_HEADER_LINK_COLOR)); ?>;
			}
		<?php
		//  =============================
		//  2.4.3 - Header Link Hover Color
		//  =============================
		?>
			.site-header a:hover, .site-header a:focus, .site-header a:active, .site-header a:visited:hover, .site-header a:visited:focus, .site-header a:visited:active {
				color: <?php echo esc_attr(get_theme_mod('dt_header_link_hover', DT_HEADER_LINK_HOVER)); ?>;
			}
	<?php
	//  =============================
	//  2.5 - Background Colors
	//  =============================
	?>
		<?php
		//  =============================
		//  2.5.1 - Header Background Color
		//  =============================
		?>
			.site-header {
				min-height: <?php echo esc_attr(get_theme_mod('dt_header_height', DT_HEADER_HEIGHT)); ?>;
				background-color: <?php echo esc_attr(get_theme_mod('dt_header_bg_color', DT_HEADER_BG_COLOR)); ?>;
				border-color: <?php echo esc_attr(get_theme_mod('dt_header_border_color', DT_HEADER_BORDER_COLOR)); ?>;
				-webkit-box-shadow: 0 1px 1px <?php echo esc_attr(get_theme_mod('dt_header_shadow_color', DT_HEADER_SHADOW_COLOR)); ?>;
				-moz-box-shadow: 0 1px 1px <?php echo esc_attr(get_theme_mod('dt_header_shadow_color', DT_HEADER_SHADOW_COLOR)); ?>;
				box-shadow: 0 1px 1px <?php echo esc_attr(get_theme_mod('dt_header_shadow_color', DT_HEADER_SHADOW_COLOR)); ?>;
			}
		<?php
		//  =============================
		//  2.5.2 - Header Border Color
		//  =============================
			// @see 2.5.1
		?>
		<?php
		//  =============================
		//  2.5.3 - Header Shadow Color
		//  =============================
			// @see 2.5.1
		?>
		<?php
		//  =============================
		//  2.5.4 - Primary Menu - Sub menu Background Color
		//  =============================
		?>
			#primary-nav ul .sub-menu a {
				background-color: <?php echo esc_attr(get_theme_mod('dt_p_nav_submenu_bg_color', DT_P_NAV_SUBMENU_BG_COLOR)); ?>;
			}
		<?php
		//  =============================
		//  2.5.5 - Primary Menu - Sub menu Background hover Color
		//  =============================
		?>
			#primary-nav ul .sub-menu a:hover {
				background-color: <?php echo esc_attr(get_theme_mod('dt_p_nav_submenu_bg_hover', DT_P_NAV_SUBMENU_BG_HOVER)); ?>;
			}
			@media (max-width: 992px) {
				#primary-nav ul li a:hover {
					background: <?php echo esc_attr(get_theme_mod('dt_p_nav_submenu_bg_hover', DT_P_NAV_SUBMENU_BG_HOVER)); ?>;
				}
			}
	<?php
	//  =============================
	//  2.6 - Typography
	//  =============================
	?>
	<?php
	//  =============================
	//  2.7 - Spacing
	//  =============================
	?>
		<?php
		//  =============================
		//  2.7.1 - Header Height
		//  =============================
			// @see 2.5.1
		?>
		<?php
		//  =============================
		//  2.7.2 - Logo Margin Right
		//  =============================
		?>
			.site-logo-wrap .site-logo,
			.site-logo-wrap h1.site-title-no-desc{
				margin-right: <?php echo esc_attr(get_theme_mod('dt_logo_margin_right', DT_LOGO_MARGIN_RIGHT)); ?>;
				margin-left: <?php echo esc_attr(get_theme_mod('dt_logo_margin_left', DT_LOGO_MARGIN_LEFT)); ?>;
				margin-top: <?php echo esc_attr(get_theme_mod('dt_logo_margin_top', DT_LOGO_MARGIN_TOP)); ?>;
			}
		<?php
		//  =============================
		//  2.7.3 - Logo Margin Left
		//  =============================
			// @see 2.7.2
		?>
		<?php
		//  =============================
		//  2.7.4 - Logo Margin Top
		//  =============================
			// @see 2.7.2
		?>
		<?php
		//  =============================
		//  2.7.5 - Primary Menu Height
		//  =============================
		?>
			#primary-nav ul li a {
				height: <?php echo esc_attr(get_theme_mod('dt_p_nav_height', DT_P_NAV_HEIGHT)); ?>;
				line-height: <?php echo esc_attr(get_theme_mod('dt_p_nav_line_height', DT_P_NAV_LINE_HEIGHT)); ?>;
			}
		<?php
		//  =============================
		//  2.7.6 - Primary Menu Line Height
		//  =============================
			// @see 2.7.5
		?>
		<?php
		//  =============================
		//  2.7.7 - Primary Menu Padding Left Right
		//  =============================
		?>
			#primary-nav ul li {
				padding: 0 <?php echo esc_attr(get_theme_mod('dt_p_nav_padding_left_right', DT_P_NAV_PADDING_LEFT_RIGHT)); ?>;
			}
        <?php
        //  =============================
        //  2.7.8 - Header Logo Width
        //  =============================
        ?>
            .site-logo-wrap{
                width: <?php echo esc_attr(get_theme_mod('dt_header_logo_width', DT_HEADER_LOGO_WIDTH)); ?>;
            }
        <?php
        //  =============================
        //  2.7.9 - Header Menu Width
        //  =============================
        ?>
            #primary-nav{
                width: <?php echo esc_attr(get_theme_mod('dt_header_menu_width', DT_HEADER_MENU_WIDTH)); ?>;
            }
	<?php
//  =============================
//  3.0 - Body
//  =============================
	?>
	<?php
	//  =============================
	//  3.1 - Background Image
	//  =============================
	?>
		<?php
		//  =============================
		//  3.1.1 - Background Image
		//  =============================
		?>
	<?php
	//  =============================
	//  3.2 - Text Colors
	//  =============================
	?>
		<?php
		//  =============================
		//  3.2.1 - Body Color
		//  =============================
			// @see 3.4.1
		?>
		<?php
		//  =============================
		//  3.2.2 - h1 to h6 Color
		//  =============================
		?>
			h1, .h1, h2, .h2, h3, .h3, h4, .h4, h5, .h5, h6, .h6, #simplemodal-container h3 {
				color: <?php echo esc_attr(get_theme_mod('dt_h1toh6_color', DT_H1TOH6_COLOR)); ?>;
			}
			#simplemodal-container h3 {
				font-family: <?php echo sanitize_text_field(get_theme_mod('dt_font_family', DT_FONT_FAMILY)); ?>;
			}
		<?php
		//  =============================
		//  3.2.3 - Link Color
		//  =============================
		?>
			a {
				color: <?php echo esc_attr(get_theme_mod('dt_link_color', DT_LINK_COLOR)); ?>;
			}
		<?php
		//  =============================
		//  3.2.4 - Link Hover Color
		//  =============================
		?>
			a:hover,
			a:visited:hover,
			a:focus,
			a:active {
				color: <?php echo esc_attr(get_theme_mod('dt_link_hover', DT_LINK_HOVER)); ?>;
			}
		<?php
		//  =============================
		//  3.2.5 - Link Visited Color
		//  =============================
		?>
			a:visited {
				color: <?php echo esc_attr(get_theme_mod('dt_link_visited', DT_LINK_VISITED)); ?>;
			}
	<?php
	//  =============================
	//  3.3 - Background Colors
	//  =============================
	?>
		<?php
		//  =============================
		//  3.3.1 - Body Background Color
		//  =============================
		?>
		<?php
		//  =============================
		//  3.3.2 - Content Box Background Color
		//  =============================
		?>
			.content-box, .content .entry, #geodir_content, .sidebar .widget, .geodir-content-left .geodir-company_info, .geodir-content-right .geodir-company_info, .geodir_full_page .geodir-category-list-in, .geodir_full_page .geodir-loc-bar {
				background-color: <?php echo esc_attr(get_theme_mod('dt_content_bg', DT_CONTENT_BG)); ?>;
				border-color: <?php echo esc_attr(get_theme_mod('dt_content_border', DT_CONTENT_BORDER)); ?>;
				box-shadow: 0 1px 1px <?php echo esc_attr(get_theme_mod('dt_content_shadow', DT_CONTENT_SHADOW)); ?>;
			}
		<?php
		//  =============================
		//  3.3.3 - Content Box Border Color
		//  =============================
			// @see 3.3.2
		?>
		<?php
		//  =============================
		//  3.3.4 - Content Box Shadow Color
		//  =============================
			// @see 3.3.2
		?>
	<?php
	//  =============================
	//  3.4 - Typography
	//  =============================
	?>
		<?php
		//  =============================
		//  3.4.1 - Font Family
		//  =============================
		?>
			body {
				font-family: <?php echo sanitize_text_field(get_theme_mod('dt_font_family', DT_FONT_FAMILY)); // sanitize_text_field used as we need to keep quotes '' ?>;
				font-size: <?php echo esc_attr(get_theme_mod('dt_font_size', DT_FONT_SIZE)); ?>;
				line-height: <?php echo esc_attr(get_theme_mod('dt_line_height', DT_LINE_HEIGHT)); ?>;
				color: <?php echo esc_attr(get_theme_mod('dt_body_color', DT_BODY_COLOR)); ?>;
			}
		<?php
		//  =============================
		//  3.4.2 - Font Size
		//  =============================
			// @see 3.4.1
		?>
		<?php
		//  =============================
		//  3.4.3 - Line Height
		//  =============================
			// @see 3.4.1
		?>
			p {
				line-height: <?php echo esc_attr(get_theme_mod('dt_line_height', '22px')); ?>;
			}
	<?php
	//  =============================
	//  3.5 - Spacing
	//  =============================
	?>
	<?php
//  =============================
//  4.0 - Footer
//  =============================
	?>
	<?php
	//  =============================
	//  4.1 - Text Colors
	//  =============================
	?>
		<?php
		//  =============================
		//  4.1.1 - Body Color
		//  =============================
		?>
			.footer-widgets {
				color: <?php echo esc_attr(get_theme_mod('dt_fw_text_color', DT_FW_TEXT_COLOR)); ?>;
			}
		<?php
		//  =============================
		//  4.1.2 - h1 to h6 Color
		//  =============================
		?>
			.footer-widgets h1,
			.footer-widgets .h1,
			.footer-widgets h2,
			.footer-widgets .h2,
			.footer-widgets h3,
			.footer-widgets .h3,
			.footer-widgets h4,
			.footer-widgets .h4,
			.footer-widgets h5,
			.footer-widgets .h5,
			.footer-widgets h6,
			.footer-widgets .h6 {
				color: <?php echo esc_attr(get_theme_mod('dt_fw_h1toh6_color', DT_FW_H1TOH6_COLOR)); ?>;
			}
		<?php
		//  =============================
		//  4.1.3 - Link Color
		//  =============================
		?>
			.footer-widgets a {
				color: <?php echo esc_attr(get_theme_mod('dt_fw_link_color', DT_FW_LINK_COLOR)); ?>;
			}
		<?php
		//  =============================
		//  4.1.4 - Link Hover Color
		//  =============================
		?>
			.footer-widgets a:hover,
			.footer-widgets a:visited:hover,
			.footer-widgets a:focus,
			.footer-widgets a:active {
				color: <?php echo esc_attr(get_theme_mod('dt_fw_link_hover', DT_FW_LINK_HOVER)); ?>;
			}
		<?php
		//  =============================
		//  4.1.5 - Link Visited Color
		//  =============================
		?>
			.footer-widgets a:visited {
				color: <?php echo esc_attr(get_theme_mod('dt_fw_link_visited', DT_FW_LINK_VISITED)); ?>;
			}
	<?php
	//  =============================
	//  4.2 - Background Colors
	//  =============================
	?>
		<?php
		//  =============================
		//  4.2.1 - Footer Section Background Color
		//  =============================
		?>
			.footer-widgets {
				background-color: <?php echo esc_attr(get_theme_mod('dt_fw_bg', DT_FW_BG)); ?>;
				border-top-color: <?php echo esc_attr(get_theme_mod('dt_fw_border_top_color', DT_FW_BORDER_TOP_COLOR)); ?>;
				border-bottom-color: <?php echo esc_attr(get_theme_mod('dt_fw_border_bottom_color', DT_FW_BORDER_BOTTOM_COLOR)); ?>;
				-webkit-box-shadow: 0 -1px 1px <?php echo esc_attr(get_theme_mod('dt_fw_box_shadow_color', DT_FW_BOX_SHADOW_COLOR)); ?>;
				-moz-box-shadow: 0 -1px 1px <?php echo esc_attr(get_theme_mod('dt_fw_box_shadow_color', DT_FW_BOX_SHADOW_COLOR)); ?>;
				box-shadow: 0 -1px 1px <?php echo esc_attr(get_theme_mod('dt_fw_box_shadow_color', DT_FW_BOX_SHADOW_COLOR)); ?>;
			}
		<?php
		//  =============================
		//  4.2.2 - Footer Section Border Top Color
		//  =============================
			// @see 4.2.1
		?>
		<?php
		//  =============================
		//  4.2.3 - Footer Section Border Bottom Color
		//  =============================
			// @see 4.2.1
		?>
		<?php
		//  =============================
		//  4.2.4 - Footer Section Box Shadow Color
		//  =============================
			// @see 4.2.1
		?>
	<?php
	//  =============================
	//  4.3 - Typography
	//  =============================
	?>
	<?php
	//  =============================
	//  4.4 - Spacing
	//  =============================
	?>
	<?php
//  =============================
//  5.0 - Copyright
//  =============================
	?>
	<?php
	//  =============================
	//  5.1 - Text Colors
	//  =============================
	?>
		<?php
		//  =============================
		//  5.1.1 - Body Color
		//  =============================
		?>
			.copyright {
				color: <?php echo esc_attr(get_theme_mod('dt_copyright_text_color', DT_COPYRIGHT_TEXT_COLOR)); ?>;
			}
		<?php
		//  =============================
		//  5.1.2 - Link Color
		//  =============================
		?>
			.copyright a {
				color: <?php echo esc_attr(get_theme_mod('dt_copyright_link_color', DT_COPYRIGHT_LINK_COLOR)); ?>;
			}
		<?php
		//  =============================
		//  5.1.3 - Link Hover Color
		//  =============================
		?>
			.copyright a:hover,
			.copyright a:visited:hover,
			.copyright a:focus,
			.copyright a:active {
				color: <?php echo esc_attr(get_theme_mod('dt_copyright_link_hover', DT_COPYRIGHT_LINK_HOVER)); ?>;
			}
		<?php
		//  =============================
		//  5.1.4 - Link Visited Color
		//  =============================
		?>
			.copyright a:visited {
				color: <?php echo esc_attr(get_theme_mod('dt_copyright_link_visited', DT_COPYRIGHT_LINK_VISITED)); ?>;
			}
	<?php
	//  =============================
	//  5.2 - Background Colors
	//  =============================
	?>
		<?php
		//  =============================
		//  5.2.1 - Copyright Section Background Color
		//  =============================
		?>
			.copyright {
				background-color: <?php echo esc_attr(get_theme_mod('dt_copyright_bg', DT_COPYRIGHT_BG)); ?>;
				border-top: 1px solid #151515;
				border-top-color: <?php echo esc_attr(get_theme_mod('dt_copyright_border_color', DT_COPYRIGHT_BORDER_COLOR)); ?>;
			}
		<?php
		//  =============================
		//  5.2.2 - Copyright Section Border Color
		//  =============================
		// @see 5.2.1
		?>
	<?php
	//  =============================
	//  5.3 - Typography
	//  =============================
	?>
	<?php
	//  =============================
	//  5.4 - Spacing
	//  =============================
	?>
		<?php
		//  =============================
		//  5.4.1 - Copyright Padding Top
		//  =============================
		?>
			.copyright .container {
				padding-top: <?php echo esc_attr(get_theme_mod('dt_copyright_padding_top', DT_COPYRIGHT_PADDING_TOP)); ?>;
				padding-bottom: <?php echo esc_attr(get_theme_mod('dt_copyright_padding_bottom', DT_COPYRIGHT_PADDING_BOTTOM)); ?>;
			}
		<?php
		//  =============================
		//  5.4.2 - Copyright Padding Bottom
		//  =============================
		// @see 5.4.1
		?>
	<?php
	//  =============================
	//  5.5 - Copyright Text
	//  =============================
	?>
		<?php
		//  =============================
		//  5.5.1 - Copyright Text
		//  =============================

}
